<?php

namespace Tarosky\RelaxWorkflow\Controller;


use Tarosky\RelaxWorkflow\Singleton;

/**
 * Settings handler.
 *
 * @package rwf
 */
class Settings extends Singleton {

	/**
	 *
	 */
	protected function init() {
		parent::init(); // TODO: Change the autogenerated stub
	}


}
